import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import bcrypt from 'bcryptjs';
import { auth } from '@/lib/auth';
import { db } from '@/lib/db';
import { users, activityLog } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';

/**
 * POST /api/admin/users
 * 
 * Create a new user for a client (SUPER_ADMIN ONLY)
 * TDD: Implementation to pass tests
 * Endpoint #3 from ADMIN-AUTOMATION-BUILD-TASK.md
 */

const createUserSchema = z.object({
  email: z.string().email('Invalid email address'),
  password: z.string().min(8, 'Password must be at least 8 characters').optional(),
  firstName: z.string().min(1, 'First name required'),
  lastName: z.string().min(1, 'Last name required'),
  clientId: z.string().uuid('Valid client ID required'),
  role: z.enum(['CLIENT', 'ADMIN']).default('CLIENT'),
});

// Helper to generate random password
function generatePassword(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%';
  let password = '';
  for (let i = 0; i < 12; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return password;
}

export async function POST(request: NextRequest) {
  try {
    // Authentication
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json(
        { error: 'Unauthorized', code: 'UNAUTHORIZED' },
        { status: 401 }
      );
    }

    // Authorization - SUPER_ADMIN or ADMIN
    if (session.user.role !== 'SUPER_ADMIN' && session.user.role !== 'ADMIN') {
      return NextResponse.json(
        { error: 'Forbidden - Admin access required', code: 'FORBIDDEN' },
        { status: 403 }
      );
    }

    const body = await request.json();
    
    // ADMIN can only create users for their own client
    if (session.user.role === 'ADMIN' && body.clientId !== session.user.clientId) {
      return NextResponse.json(
        { error: 'Forbidden - Can only create users for your own client', code: 'FORBIDDEN' },
        { status: 403 }
      );
    }
    
    // Validation
    const validation = createUserSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          code: 'VALIDATION_ERROR',
          details: validation.error.flatten(),
        },
        { status: 400 }
      );
    }

    const { email, firstName, lastName, clientId, role } = validation.data;
    
    // Auto-generate password if not provided
    const plainPassword = validation.data.password || generatePassword();
    const wasAutoGenerated = !validation.data.password;

    // Check if user already exists
    const existingUser = await db.query.users.findFirst({
      where: eq(users.email, email),
    });

    if (existingUser) {
      return NextResponse.json(
        { error: 'User with this email already exists', code: 'DUPLICATE_EMAIL' },
        { status: 409 }
      );
    }

    // Verify client exists
    const client = await db.query.clients.findFirst({
      where: (clients, { eq }) => eq(clients.id, clientId),
    });

    if (!client) {
      return NextResponse.json(
        { error: 'Client not found', code: 'CLIENT_NOT_FOUND' },
        { status: 404 }
      );
    }

    // Hash password
    const passwordHash = await bcrypt.hash(plainPassword, 10);

    // Create user
    const newUser = await db.insert(users).values({
      email,
      passwordHash,
      firstName,
      lastName,
      role,
      clientId,
      isActive: true,
      mustChangePassword: wasAutoGenerated, // Force password change if auto-generated
    }).returning();

    // Log activity
    await db.insert(activityLog).values({
      userId: session.user.id,
      clientId: clientId,
      action: 'USER_CREATED',
      details: `Created user: ${email} (${firstName} ${lastName}) with role ${role}`,
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    }).catch(err => {
      console.warn('Failed to log activity:', err);
      // Don't fail the request if logging fails
    });

    // Return with password if auto-generated
    return NextResponse.json(
      {
        success: true,
        user: {
          id: newUser[0].id,
          email: newUser[0].email,
          firstName: newUser[0].firstName,
          lastName: newUser[0].lastName,
          role: newUser[0].role,
          clientId: newUser[0].clientId,
        },
        ...(wasAutoGenerated && { 
          generatedPassword: plainPassword,
          message: 'User created with auto-generated password. Please share this password with the user securely.',
        }),
      },
      { status: 201 }
    );

  } catch (error) {
    console.error('Error creating user:', error);
    return NextResponse.json(
      { error: 'Internal server error', code: 'SERVER_ERROR' },
      { status: 500 }
    );
  }
}

/**
 * GET /api/admin/users
 * 
 * Get all users (ADMIN or SUPER_ADMIN)
 */
export async function GET(request: NextRequest) {
  try {
    // Authentication
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json(
        { error: 'Unauthorized', code: 'UNAUTHORIZED' },
        { status: 401 }
      );
    }

    // Authorization - ADMIN or SUPER_ADMIN
    if (session.user.role !== 'ADMIN' && session.user.role !== 'SUPER_ADMIN') {
      return NextResponse.json(
        { error: 'Forbidden - Admin access required', code: 'FORBIDDEN' },
        { status: 403 }
      );
    }

    // Fetch all users with client info
    const allUsers = await db.query.users.findMany({
      orderBy: (users, { desc }) => [desc(users.createdAt)],
    });

    // Get client names
    const clients = await db.query.clients.findMany();
    const clientMap = new Map(clients.map(c => [c.id, c.companyName]));

    const usersWithClientName = allUsers.map(u => ({
      id: u.id,
      email: u.email,
      firstName: u.firstName,
      lastName: u.lastName,
      role: u.role,
      clientId: u.clientId,
      clientName: u.clientId ? clientMap.get(u.clientId) : null,
      isActive: u.isActive,
      lastLoginAt: u.lastLoginAt,
      createdAt: u.createdAt,
    }));

    return NextResponse.json({
      success: true,
      users: usersWithClientName,
      count: usersWithClientName.length,
    });

  } catch (error) {
    console.error('Error fetching users:', error);
    return NextResponse.json(
      { error: 'Internal server error', code: 'SERVER_ERROR' },
      { status: 500 }
    );
  }
}

