services:
  # Main Web Service
  - type: web
    name: uysp-portal-v2
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Configured manually in Render dashboard
      - key: NEXTAUTH_SECRET
        sync: false  # Configured manually in Render dashboard
      - key: NEXTAUTH_URL
        sync: false  # Configured manually in Render dashboard
      - key: AIRTABLE_API_KEY
        sync: false  # Configured manually in Render dashboard
      - key: AIRTABLE_BASE_ID
        sync: false  # Configured manually in Render dashboard
      - key: SMTP_USER
        sync: false  # Configured manually in Render dashboard
      - key: SMTP_PASSWORD
        sync: false  # Configured manually in Render dashboard
      - key: SMTP_FROM_EMAIL
        sync: false  # Configured manually in Render dashboard
      - key: SMTP_FROM_NAME
        sync: false  # Configured manually in Render dashboard
      - key: CRON_SECRET
        generateValue: true  # Render will auto-generate a secure secret
    healthCheckPath: /
    autoDeploy: true

  # Cron Job: Process Airtable Sync Queue
  - type: cron
    name: process-sync-queue
    runtime: node
    schedule: "*/5 * * * *"  # Every 5 minutes
    buildCommand: npm install
    startCommand: |
      curl -X POST \
        -H "Authorization: Bearer $CRON_SECRET" \
        -H "Content-Type: application/json" \
        https://uysp-portal-v2.onrender.com/api/cron/process-sync-queue
    envVars:
      - key: CRON_SECRET
        fromService:
          type: web
          name: uysp-portal-v2
          envVarKey: CRON_SECRET

  # Cron Job: Weekly Report (existing)
  - type: cron
    name: weekly-report
    runtime: node
    schedule: "0 9 * * 1"  # Every Monday at 9am UTC
    buildCommand: npm install
    startCommand: |
      curl -X POST \
        -H "Authorization: Bearer $CRON_SECRET" \
        -H "Content-Type: application/json" \
        https://uysp-portal-v2.onrender.com/api/cron/weekly-report
    envVars:
      - key: CRON_SECRET
        fromService:
          type: web
          name: uysp-portal-v2
          envVarKey: CRON_SECRET
